services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Service\:
        resource: '../../../src/Service/*'
    App\Command\:
        resource: '../../../src/Command/*'
